
variables:
  python.version: '3.6'

pool:
  vmImage: 'Ubuntu 16.04'

phases:

- phase: 'Self test'
  queue: 'Ubuntu 16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      pip install aiohttp
      cd ./test
      python ./self_test.py
    displayName: 'self-test'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Selftest'
    condition: succeededOrFailed()